#!/usr/bin/bash
declare -i o
# looping through arguments
for (( i=1;i<=$#;i++ ));
do
	case ${@:i:1} in
		# checking for -o option and fetching the next argument as argument for the option
		-o|--offset)
			if [[ "${@:i+1:1}" =~ [[:digit:]]*[[:blank:]]*$ ]]; then
				o+="${@:i+1:1}"
			else
				echo "option -o/--offset received incorrect argument"
				echo "Enter only a number"
			fi
			;;
		# checking for -f option and checking if next argument is a valid file
		# overwriting the previous file is intended behaviour
		-f|--file)
			if [[ -f "${@:i+1:1}" ]]; then
				f="${@:i+1:1}"
			else
				echo "option -f/--file received incorrect argument"
				echo "Enter Valid File"
			fi
			;;
		# checking for -r option
		-r|--random)
			r=$RANDOM
			;;
		# checking for '=' style options 
		# ------------------------------------------------------
		-o=*|--offset=*)
			if [[ "${@:i:1}" =~ (-o|--offset)=[[:digit:]][[:blank:]]* ]]; then
				o+=$(echo ${@:i:1} | sed -E "s/(-o|--offset)=([[:digit:]]*)/\2/")
			else
				echo "option -o/-offset can't parse the given argument"
				echo "Enter only a number with no space on either side of '='"
			fi
			;;
		-f=*|--file=*)
			reg=$(echo "${@:i:1}" | sed -E "s/(-f|--file)=([[:alnum:]]*)/\2/")
			if [ -f "$reg" ]; then
				f="$reg"
			else
				echo "option -f/--file received incorrect argument"
				echo "Enter Valid FIle"
			fi		
		# ------------------------------------------------------
			
	esac
		
done
echo "$o" "$f" "$r"
